version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:jessie
    steps:
      - run:
          name: Prepare env
          command: "sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libfreeimage-dev libglew-dev libxi-dev libglfw3 -y"
      - checkout
      - run:
          name: Update yarn
          command: "sudo npm i -g yarn"
      - run:
          name: Install project dependencies
          command: "yarn install"
      - run:
          name: Test
          command: yarn test
      - run:
          name: Generate code coverage
          command: "./node_modules/.bin/nyc report --reporter=text-lcov"
      - store_artifacts:
          path: test-results.xml
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
